aws:
  s3:
    accessKey: "ASIAR7HWXTTRX2GHTOWI"
    secretKey: "f+lWIPgzXVSk7tD4F/yAcvFXnCvGD2zZ66n89TFl"
    sessionToken: "IQoJb3JpZ2luX2VjEPb//////////wEaCXVzLXdlc3QtMiJIMEYCIQDqUt2INu5wokJK3NecyNh3mDBMSf8keDotyVVXAzy3LQIhAJhyzMGngMOjHcOiv2chgchjyHCvsJY6t32S1kB6c6dZKoUECL///////////wEQABoMMTM1ODA4OTE2NzA3IgxHuk+dvD6l3GDpwZEq2QPFE/5g8x898ca9abQuBjdfQbkRVJuJYWSj6mBpdtH9ezsJM+wtSgjFb23ULIY6iW+3smarKd3Z0GkdfWlUYvfHK6eOOh4isPnpl29iPnCPKAsovjOsY5YcMVyC8bCwfVrvWNnO8GzxFLMrP17JpG1afajamu/6yoAgQIoohKw43PEYDbpjHSfcwBbzcnvmz9/ROC7lvAHc9cYlbpcsZIMzJGyHA5NbmDhc1FDBEJZvSc1KdLhQ/DrRDkXktmR0ma1WkXC60WQc8mBX4S9spmb7QBdpnOtzuDTz77+Lvb1KhtGAyYWsW8m9BpoW2Bl2HETjTDVz/1zEc0ess9JnsvyS/Or0xrDYeklVz/CR8bMs8q3ju2MjIlF41+8/TZvFx6wdMbTwjdKALY1+JMYYcqiAYlboUEJ4TSMVIK7hxL8rLr3YiS9PAmiQhKx4ARorWvKo3CE03E9EObdEcbHyVnNcCxkD57mBMWvLgwY4oWgDnO6FcWlVNuEW00FSnspUL/8W4LhK0xnq+AzkHU6t4smQeXn+gOAE/IjXtSbpHS1ydfeKne8rY6ME6Qe8MzHczl8NUgm3SSfHnwh1RlSPsn4MUBwH98ozQBEHx1r3M0tEstUGAn/IOlcrUTCbk9XRBjqnAYjJGgi+TUtlc9HBeByU/IxKCLfWwmwim7izcGFtTVOt/GtGsXq/G0K1uWU+gJ1sPZFRt1UaBk7skllXJ9kDL3735Pe1U4031+s8C1nBHQJxKb4GLSMLDr7uK/hvna/o3+ZK2pnasmP3z4lVFm/dPxLDxPx0Bj/cF00/XN9kj87h1SAy6HHHq9Zw30+LS6Q/g1Ma0gxPIR9U0C9J9BApgHHpCQIjYJ9M"
    region: "us-west-2"
    bucketName: "twist-api-purchase-orders"
    archivePath: "archive/"

idp:
  host: "idp-rt.us-east-1.anypoint.mulesoft.com"
  port: "443"
  basePath: "/api/v1"
  clientId: "06e27b9938c346af9b882e07288702d6"
  clientSecret: "475c0CC8Fff846e4b16035C8F2D9EbA5"
  actionId: "12345-po-extraction"

salesforce:
  username: "mulesoftapi@twistbioscience.com"
  password: "Twist@2026"
  securityToken: "e99A2VlFmuZdCWsg2LDEzK6uA"
  consumerKey: "3MVG9j59pXC2nTiefNV4f_.gxBsw7Lk_0a4Z01roGDM2bX8NWB6Cc4oV7xpnqaYVRSJvxPCafNuHwgpPAJohj"
  consumerSecret: "83C9465BCDC37B8AAAADEB87B73AA588258D189B0C75A3DF7DA3B344E8ABBEB8"
  tokenEndpoint: "https://twistbioscience--pdxqa.sandbox.my.salesforce.com/services/oauth2/token"


  apiversion: "54.0"
 # host: "https://newportnewscu--zenndev.sandbox.my.salesforce.com/" #Production or Developer Edition use My Domain (also can use login.salesforce.com if domain not forced)
  #username: "integration.user@bayportcu.org"
  #consumerKey: "3MVG9cHH2bfKACZbw3AJODO5licG4iteveVFiO_ag2jjSlGvuvgw0bWHho3ySJcg0NvwvUma2_p.5TRNUsm1H" #Consumer key/id of Connected App created in Salesforce with public certificate exported/uploaded from private keystore. Must have api and refresh_token scopes allowed.
  jwt:
    audience: "https://login.salesforce.com" #Production with My Domain must use login.salesforce.com
    keypath: "jwt/sfdc-keystore-dev.jks" #This jks generated and exported from Salesforce Certificate and Key Management (Setup Menu)
    keypass: "SFDCDevKey" #use secure:: file property decrypted at deployment
    crtalias: "mulesfdcdev" #alias will be lowercase
  bulk:
    lineEnding: "CRLF" #Windows local machine
    monitorRetries: "40"
    monitorFrequency: "5000" #milliseconds
  limits:
    dmlSync: "200" #max records synchronous DML operation