api:
  id: "21042601"

anypoint:
  platform:
    client_id: "f9b0ac75792248cc9a3ead127a0ea437"
    client_secret: "e2f7f19d6bA8425894c06D7e39499683"

aws:
  s3:
    roleArn: "arn:aws:iam::749602843853:role/twist-api-purchase-orders-role"
    region: "us-east-1"
    bucketName: "twist-api-purchase-orders-qa"
    archivePath: "archive/"
  accessKey: "ASIA25B6PVTGZYLO2HEE"
  secretKey: "wA5qm66jDbdZOIJwRR8Ub0AekApO/tuzRJw9or1l"
  sessionToken: "IQoJb3JpZ2luX2VjEPf//////////wEaCXVzLWVhc3QtMSJHMEUCIBiDapHOmRKl4pRfRycz2cK4jEfuyPuYKz8hlaPYswANAiEA4H1aozlRUCYA7Rsnnh3o+/TY6LF9uETKYxTnJOJ6F9wqqAQIwP//////////ARADGgw3NDk2MDI4NDM4NTMiDC+7JA/m5n9uPjlSKir8A7qdhzgfQkxu2RpDsl/yIxwYtt4XRrvxq2/nk/gyPc3pPIx7Sky567MLYMzLRfmS1vB26xRazp9SixnEvEgcmu9Zp/f4+qw6rpnvgO4pvvC/cOc8aOGdlgTPebl2vK6J1aSYne8FWuD61lh3Wr9BQ1jKQwF8gaLYm+ANdOVdupkR9qPBPcZbvPgy70Oic6SS3snfzsXJx222zeix36QoCvSn0h74OJRLFcUobbMe5PN0bhFlKef2wXzWFCc/x7hvyZGhNS91EHFIM5mlOkVVaoYEHB3c8teRBNYMgDusKJ9c48R5Mx376GaJEi1SEbCkXBMV5PjXf7EQsDOai5+GJ2Iht3Wg0gXxaNlLIRH4XojB4qrKoKgJX/QtfNyGEZmkGhLmnaXwBDXv86Lirew/U3GMHUz/7h2jcX94Sag/2uvDW/EOPgDuI7GqlDpfGbaEq6lqpTGyO1+T/4gmPJ7jI/j9+8KSw6xlzDr3p1Lv2iIBm4Cw0WpQdfeDPfMcPg4MEcqDCs4jrRdi0gXlmhr1C7tnPFGIbOK6TPyUU8t+boMR8W598GJDQmiGIS6gdCRLV2ITwrd/4ZaQpIosmgB89j/+XS5RgHW4yRaWamwXIGQaQmtbiAmOiQNIuPXoOI0KLpnYFlN4mVTwU6OhetGCVLMxGWF3DVRoU1aXv58w643+0gY6qAGqA58s7BSfed2dhl1QtJICqBx8yWgg9yWDc6D7s4IMj3Xa1/kJqGDz6YMTTTYQrQfq4Ignsadck2T9Xu1rLGmnM7aDwsZVBF8f+8p/Da09wLLvfd1wnwrGSmYeDN3SkZqOV1qtGX4McAebDjdcUyBadLkY92Jk2u6lLQ/xUU9ecnUUoyvnFVLyj3ffwXK1CX9mNyoFCz5JWOoDv9S82pexqcIbaSFnTEw="
  
idp:
  host: "idp-rt.us-east-1.anypoint.mulesoft.com"
  port: "443"
  basePath: "/api/v1"
  clientId: "16e5c838bf1d4e88883b58012693161b"
  clientSecret: "e35f8c788ae24a1fB7A73305f46c4268"
  actionId: "6ca5506c-6028-4dd8-8309-38be403da995"
  orgId: "1b779604-67d0-4285-87b7-be5e6af3ba19"

salesforce:
  username: "mulesoftapi@twistbioscience.com"
  password: "Twist@2026"
  securityToken: "e99A2VlFmuZdCWsg2LDEzK6uA"
  consumerKey: "3MVG96yD8KRvY2.HIrks1tm6upzdiXbDsRWf8c1UfUgN_ZS5WU4boDHrLC7o5kPEUxky0IK_mzypX2AqoUBfw"
  consumerSecret: "83C9465BCDC37B8AAAADEB87B73AA588258D189B0C75A3DF7DA3B344E8ABBEB8"
  tokenEndpoint: "https://twistbioscience--pdx.sandbox.my.salesforce.com/services/oauth2/token"
  principal: "mulesoftapi@twistbioscience.com.pdx"
  apiversion: "54.0"
  jwt:
    audience: "https://login.salesforce.com"
    keypath: "jwt/sfdc-keystore-dev.jks"
    keypass: "SFDCDevKey"
    crtalias: "mulesfdcdev"
  bulk:
    lineEnding: "CRLF"
    monitorRetries: "40"
    monitorFrequency: "5000"
  limits:
    dmlSync: "200"